version: '3'

services:
    uwpath_frontend:
      image: uwpath_frontend
      container_name: uwpath_frontend
      build: .
      ports:
        - "8080:8080"
        - "443:443"
      networks:
        - uwpath_backend_network

networks:
  uwpath_backend_network:
    external: true